shared:
  # TODO: Test data that we can delete once demo'ed
  "i want to test best bets":
    - /government/people/test-person
    - /government/publications/test--150
    - /service-manual/technology/test-your-services-performance
  "budget": 
    - /government/topical-events/budget-2025
    - /government/publications/budget-2025
  "budget 2025":
    - /government/topical-events/budget-2025
    - /government/publications/budget-2025
  "autumn budget": /government/topical-events/budget-2025
  "autumn budget 2025": /government/topical-events/budget-2025
  "2025 budget": /government/topical-events/budget-2025
  "budget november 2025": /government/topical-events/budget-2025
  "budget statement": /government/topical-events/budget-2025
  "autumn statement": /government/topical-events/budget-2025
  "the budget": /government/topical-events/budget-2025
  "budget documents": /government/publications/budget-2025
  "gaza":
    - /foreign-travel-advice/the-occupied-palestinian-territories
    - /government/news/gaza-what-you-can-do-to-help
    - /government/publications/humanitarian-situation-in-gaza-the-uk-governments-response/humanitarian-situation-in-gaza-the-uk-governments-response
  "palestine":
    - /foreign-travel-advice/the-occupied-palestinian-territories
    - /government/news/gaza-what-you-can-do-to-help
    - /government/publications/humanitarian-situation-in-gaza-the-uk-governments-response/humanitarian-situation-in-gaza-the-uk-governments-response
  "antisocial behaviour": /how-report-antisocial-behaviour
  "anti social behaviour": /how-report-antisocial-behaviour
  "anti-social behaviour": /how-report-antisocial-behaviour
  "contact hmrc": /contact-hmrc
  "mediation": /find-legal-advice
  "ombudsman": /find-legal-advice
  "plan for change": /missions
  "eta": /eta
  "paying hmrc": /government/collections/paying-hmrc-detailed-information
  "new style jsa": /jobseekers-allowance
  "new style esa": /employment-support-allowance

test:
  "i want to test a single best bet": /here/you/go
  "i want to test multiple best bets":
    - /i-am-important
    - /i-am-also-important
    - /also-me
